In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime

In [2]:
players = pd.read_csv('C:/Users/parks/OneDrive/바탕 화면/DATASET/Football/players.csv')
clubs = pd.read_csv('C:/Users/parks/OneDrive/바탕 화면/DATASET/Football/clubs.csv')
valuations = pd.read_csv('C:/Users/parks/OneDrive/바탕 화면/DATASET/Football/player_valuations.csv')
games = pd.read_csv('C:/Users/parks/OneDrive/바탕 화면/DATASET/Football/games.csv')
lineup = pd.read_csv('C:/Users/parks/OneDrive/바탕 화면/DATASET/Football/game_lineups.csv')
club_games = pd.read_csv('C:/Users/parks/OneDrive/바탕 화면/DATASET/Football/club_games.csv')
game_events = pd.read_csv('C:/Users/parks/OneDrive/바탕 화면/DATASET/Football/game_events.csv')
competitions = pd.read_csv('C:/Users/parks/OneDrive/바탕 화면/DATASET/Football/competitions.csv')
appearances = pd.read_csv('C:/Users/parks/OneDrive/바탕 화면/DATASET/Football/appearances.csv')

In [3]:
competitions = competitions.drop('url', axis=1)
competitions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   competition_id            43 non-null     object
 1   competition_code          43 non-null     object
 2   name                      43 non-null     object
 3   sub_type                  43 non-null     object
 4   type                      43 non-null     object
 5   country_id                43 non-null     int64
 6   country_name              36 non-null     object
 7   domestic_league_code      36 non-null     object
 8   confederation             43 non-null     object
 9   is_major_national_league  43 non-null     bool
dtypes: bool(1), int64(1), object(8)
memory usage: 3.2+ KB

In [4]:
competitions['competition_id'].unique()

array(['CIT', 'NLSC', 'GRP', 'POSU', 'RUSS', 'SUC', 'USC', 'DK1', 'EL',
       'ES1', 'FR1', 'IT1', 'NL1', 'RUP', 'PO1', 'BESC', 'GB1', 'ELQ',
       'CGB', 'DKP', 'ECLQ', 'FAC', 'NLP', 'UKRS', 'UKR1', 'CDR', 'CL',
       'GR1', 'TR1', 'POCP', 'GBCS', 'KLUB', 'L1', 'RU1', 'SC1', 'SCI',
       'BE1', 'CLQ', 'DFL', 'SFA', 'UKRP', 'DFB', 'FRCH'], dtype=object)

In [5]:
appearances.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1556969 entries, 0 to 1556968
Data columns (total 13 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   appearance_id           1556969 non-null  object
 1   game_id                 1556969 non-null  int64
 2   player_id               1556969 non-null  int64
 3   player_club_id          1556969 non-null  int64
 4   player_current_club_id  1556969 non-null  int64
 5   date                    1556969 non-null  object
 6   player_name             1556963 non-null  object
 7   competition_id          1556969 non-null  object
 8   yellow_cards            1556969 non-null  int64
 9   red_cards               1556969 non-null  int64
 10  goals                   1556969 non-null  int64
 11  assists                 1556969 non-null  int64
 12  minutes_played          1556969 non-null  int64
dtypes: int64(9), object(4)
memory usage: 154.4+ MB

In [6]:
games = games.drop('url', axis=1)
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67421 entries, 0 to 67420
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 67421 non-null  int64
 1   competition_id          67421 non-null  object
 2   season                  67421 non-null  int64
 3   round                   67421 non-null  object
 4   date                    67421 non-null  object
 5   home_club_id            67421 non-null  int64
 6   away_club_id            67421 non-null  int64
 7   home_club_goals         67421 non-null  int64
 8   away_club_goals         67421 non-null  int64
 9   home_club_position      47449 non-null  float64
 10  away_club_position      47449 non-null  float64
 11  home_club_manager_name  66675 non-null  object
 12  away_club_manager_name  66675 non-null  object
 13  stadium                 67207 non-null  object
 14  attendance              57718 non-null  float64
 15  referee                 66823 non-null  object
 16  home_club_formation     60823 non-null  object
 17  away_club_formation     60969 non-null  object
 18  home_club_name          55971 non-null  object
 19  away_club_name          57209 non-null  object
 20  aggregate               67421 non-null  object
 21  competition_type        67421 non-null  object
dtypes: float64(3), int64(6), object(13)
memory usage: 11.3+ MB

In [7]:
df = pd.merge(games, competitions, on='competition_id', how='left')
df

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,competition_type,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,is_major_national_league
0,2321044,L1,2013,2. Matchday,2013-08-18,16,23,2,1,1.0,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
1,2321060,L1,2013,3. Matchday,2013-08-25,23,24,0,2,18.0,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
2,2321086,L1,2013,6. Matchday,2013-09-21,4,16,1,1,15.0,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
3,2321152,L1,2013,11. Matchday,2013-11-02,44,33,0,2,7.0,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
4,2321205,L1,2013,17. Matchday,2013-12-21,41,39,2,3,14.0,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67416,2629035,NLP,2015,Third Round,2015-10-27,383,16866,6,0,NaN,...,domestic_cup,toto-knvb-beker,toto-knvb-beker,domestic_cup,domestic_cup,122,Netherlands,NL1,europa,False
67417,3092951,CLQ,2018,Qualifying Round 2nd leg,2018-08-29,383,713,3,0,NaN,...,international_cup,uefa-champions-league-qualifikation,uefa-champions-league-qualifikation,uefa_champions_league_qualifying,international_cup,-1,NaN,NaN,europa,False
67418,4164101,CGB,2023,Second Round,2023-08-29,512,1194,6,1,NaN,...,other,efl-cup,efl-cup,league_cup,other,189,England,GB1,europa,False
67419,3143618,FAC,2018,Third Round Replay,2019-01-15,512,3054,2,3,NaN,...,domestic_cup,fa-cup,fa-cup,domestic_cup,domestic_cup,189,England,GB1,europa,False
67420,4233201,SFA,2023,Fourth Round,2024-01-20,987,3020,3,1,NaN,...,domestic_cup,sfa-cup,sfa-cup,domestic_cup,domestic_cup,190,Scotland,SC1,europa,False

In [8]:
df['name'].unique()

array(['bundesliga', 'premier-liga', 'jupiler-pro-league', 'ligue-1',
       'premier-league', 'scottish-premiership', 'liga-portugal-bwin',
       'laliga', 'eredivisie', 'super-lig', 'super-league-1', 'serie-a',
       'allianz-cup', 'europa-league', 'ukrainian-cup',
       'uefa-champions-league', 'copa-del-rey', 'italy-cup', 'fa-cup',
       'kypello-elladas', 'community-shield',
       'uefa-champions-league-qualifikation', 'toto-knvb-beker',
       'superligaen', 'dfb-pokal', 'russian-cup', 'sydbank-pokalen',
       'europa-league-qualifikation', 'supertaca-candido-de-oliveira',
       'sfa-cup', 'supercopa', 'fifa-klub-wm', 'efl-cup',
       'uefa-europa-conference-league-qualifikation', 'uefa-super-cup',
       'supercoppa-italiana', 'dfl-supercup', 'trophee-des-champions',
       'ukrainian-super-cup', 'russian-super-cup', 'johan-cruijff-schaal',
       'belgian-supercup'], dtype=object)

In [9]:
df[df['sub_type'] != 'fifa_club_world_cup']

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,competition_type,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,is_major_national_league
0,2321044,L1,2013,2. Matchday,2013-08-18,16,23,2,1,1.0,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
1,2321060,L1,2013,3. Matchday,2013-08-25,23,24,0,2,18.0,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
2,2321086,L1,2013,6. Matchday,2013-09-21,4,16,1,1,15.0,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
3,2321152,L1,2013,11. Matchday,2013-11-02,44,33,0,2,7.0,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
4,2321205,L1,2013,17. Matchday,2013-12-21,41,39,2,3,14.0,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67416,2629035,NLP,2015,Third Round,2015-10-27,383,16866,6,0,NaN,...,domestic_cup,toto-knvb-beker,toto-knvb-beker,domestic_cup,domestic_cup,122,Netherlands,NL1,europa,False
67417,3092951,CLQ,2018,Qualifying Round 2nd leg,2018-08-29,383,713,3,0,NaN,...,international_cup,uefa-champions-league-qualifikation,uefa-champions-league-qualifikation,uefa_champions_league_qualifying,international_cup,-1,NaN,NaN,europa,False
67418,4164101,CGB,2023,Second Round,2023-08-29,512,1194,6,1,NaN,...,other,efl-cup,efl-cup,league_cup,other,189,England,GB1,europa,False
67419,3143618,FAC,2018,Third Round Replay,2019-01-15,512,3054,2,3,NaN,...,domestic_cup,fa-cup,fa-cup,domestic_cup,domestic_cup,189,England,GB1,europa,False
67420,4233201,SFA,2023,Fourth Round,2024-01-20,987,3020,3,1,NaN,...,domestic_cup,sfa-cup,sfa-cup,domestic_cup,domestic_cup,190,Scotland,SC1,europa,False

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67421 entries, 0 to 67420
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   game_id                   67421 non-null  int64
 1   competition_id            67421 non-null  object
 2   season                    67421 non-null  int64
 3   round                     67421 non-null  object
 4   date                      67421 non-null  object
 5   home_club_id              67421 non-null  int64
 6   away_club_id              67421 non-null  int64
 7   home_club_goals           67421 non-null  int64
 8   away_club_goals           67421 non-null  int64
 9   home_club_position        47449 non-null  float64
 10  away_club_position        47449 non-null  float64
 11  home_club_manager_name    66675 non-null  object
 12  away_club_manager_name    66675 non-null  object
 13  stadium                   67207 non-null  object
 14  attendance                57718 non-null  float64
 15  referee                   66823 non-null  object
 16  home_club_formation       60823 non-null  object
 17  away_club_formation       60969 non-null  object
 18  home_club_name            55971 non-null  object
 19  away_club_name            57209 non-null  object
 20  aggregate                 67421 non-null  object
 21  competition_type          67421 non-null  object
 22  competition_code          67421 non-null  object
 23  name                      67421 non-null  object
 24  sub_type                  67421 non-null  object
 25  type                      67421 non-null  object
 26  country_id                67421 non-null  int64
 27  country_name              59195 non-null  object
 28  domestic_league_code      59195 non-null  object
 29  confederation             67421 non-null  object
 30  is_major_national_league  67421 non-null  bool
dtypes: bool(1), float64(3), int64(7), object(20)
memory usage: 15.5+ MB

In [11]:
clubs = clubs.drop(['url', 'filename'], axis=1)
clubs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   club_id                  426 non-null    int64
 1   club_code                426 non-null    object
 2   name                     426 non-null    object
 3   domestic_competition_id  426 non-null    object
 4   total_market_value       0 non-null      float64
 5   squad_size               426 non-null    int64
 6   average_age              388 non-null    float64
 7   foreigners_number        426 non-null    int64
 8   foreigners_percentage    378 non-null    float64
 9   national_team_players    426 non-null    int64
 10  stadium_name             426 non-null    object
 11  stadium_seats            426 non-null    int64
 12  net_transfer_record      426 non-null    object
 13  coach_name               0 non-null      float64
 14  last_season              426 non-null    int64
dtypes: float64(4), int64(6), object(5)
memory usage: 50.0+ KB

In [12]:
clubs

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season
0,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,NaN,31,26.6,11,35.5,1,Merck-Stadion am Böllenfalltor,17810,€-1.48m,NaN,2023
1,11127,ural-ekaterinburg,FK Ural Yekaterinburg,RU1,NaN,27,27.9,15,55.6,6,Yekaterinburg Arena,23000,€-895k,NaN,2023
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,TR1,NaN,35,26.7,17,48.6,13,Tüpraş Stadyumu,42590,€-26.00m,NaN,2023
3,12,as-rom,Associazione Sportiva Roma,IT1,NaN,26,26.9,18,69.2,16,Olimpico di Roma,73261,+€63.00m,NaN,2023
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,NaN,26,25.4,20,76.9,21,Tottenham Hotspur Stadium,62850,€-151.40m,NaN,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,68608,cf-os-belenenses,CF Os Belenenses,PO1,NaN,30,25.7,5,16.7,0,Estádio do Restelo,19980,+-0,NaN,2017
422,724,fc-volendam,Football Club Volendam,NL1,NaN,31,22.2,17,54.8,4,Kras Stadion,7384,+€2.30m,NaN,2023
423,800,atalanta-bergamo,Atalanta Bergamasca Calcio S.p.a.,IT1,NaN,25,26.6,17,68.0,16,Gewiss Stadium,21747,+€73.82m,NaN,2023
424,979,moreirense-fc,Moreirense Futebol Clube,PO1,NaN,29,25.7,17,58.6,3,Estádio C. J. de Almeida Freitas,6153,€-2.05m,NaN,2023
425,984,west-bromwich-albion,West Bromwich Albion,GB1,NaN,25,27.8,8,32.0,4,The Hawthorns,26850,€-1.35m,NaN,2020

In [13]:
clubs['total_market_value'].unique()

array([nan])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67421 entries, 0 to 67420
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   game_id                   67421 non-null  int64
 1   competition_id            67421 non-null  object
 2   season                    67421 non-null  int64
 3   round                     67421 non-null  object
 4   date                      67421 non-null  object
 5   home_club_id              67421 non-null  int64
 6   away_club_id              67421 non-null  int64
 7   home_club_goals           67421 non-null  int64
 8   away_club_goals           67421 non-null  int64
 9   home_club_position        47449 non-null  float64
 10  away_club_position        47449 non-null  float64
 11  home_club_manager_name    66675 non-null  object
 12  away_club_manager_name    66675 non-null  object
 13  stadium                   67207 non-null  object
 14  attendance                57718 non-null  float64
 15  referee                   66823 non-null  object
 16  home_club_formation       60823 non-null  object
 17  away_club_formation       60969 non-null  object
 18  home_club_name            55971 non-null  object
 19  away_club_name            57209 non-null  object
 20  aggregate                 67421 non-null  object
 21  competition_type          67421 non-null  object
 22  competition_code          67421 non-null  object
 23  name                      67421 non-null  object
 24  sub_type                  67421 non-null  object
 25  type                      67421 non-null  object
 26  country_id                67421 non-null  int64
 27  country_name              59195 non-null  object
 28  domestic_league_code      59195 non-null  object
 29  confederation             67421 non-null  object
 30  is_major_national_league  67421 non-null  bool
dtypes: bool(1), float64(3), int64(7), object(20)
memory usage: 15.5+ MB

In [15]:
df2 = pd.merge(clubs, df, left_on='domestic_competition_id', right_on='competition_id', how='inner')
df2

,club_id,club_code,name_x,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,...,competition_type,competition_code,name_y,sub_type,type,country_id,country_name,domestic_league_code,confederation,is_major_national_league
0,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,NaN,31,26.6,11,35.5,1,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
1,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,NaN,31,26.6,11,35.5,1,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
2,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,NaN,31,26.6,11,35.5,1,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
3,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,NaN,31,26.6,11,35.5,1,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
4,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,NaN,31,26.6,11,35.5,1,...,domestic_league,bundesliga,bundesliga,first_tier,domestic_league,40,Germany,L1,europa,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1492001,347,fc-metz,Football Club de Metz,FR1,NaN,28,25.0,21,75.0,10,...,domestic_league,ligue-1,ligue-1,first_tier,domestic_league,50,France,FR1,europa,True
1492002,347,fc-metz,Football Club de Metz,FR1,NaN,28,25.0,21,75.0,10,...,domestic_league,ligue-1,ligue-1,first_tier,domestic_league,50,France,FR1,europa,True
1492003,347,fc-metz,Football Club de Metz,FR1,NaN,28,25.0,21,75.0,10,...,domestic_league,ligue-1,ligue-1,first_tier,domestic_league,50,France,FR1,europa,True
1492004,347,fc-metz,Football Club de Metz,FR1,NaN,28,25.0,21,75.0,10,...,domestic_league,ligue-1,ligue-1,first_tier,domestic_league,50,France,FR1,europa,True
1492005,347,fc-metz,Football Club de Metz,FR1,NaN,28,25.0,21,75.0,10,...,domestic_league,ligue-1,ligue-1,first_tier,domestic_league,50,France,FR1,europa,True

In [16]:
df2 = df2.drop(['total_market_value', 'coach_name'], axis=1)

In [17]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1492006 entries, 0 to 1492005
Data columns (total 44 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   club_id                   1492006 non-null  int64
 1   club_code                 1492006 non-null  object
 2   name_x                    1492006 non-null  object
 3   domestic_competition_id   1492006 non-null  object
 4   squad_size                1492006 non-null  int64
 5   average_age               1387145 non-null  float64
 6   foreigners_number         1492006 non-null  int64
 7   foreigners_percentage     1357508 non-null  float64
 8   national_team_players     1492006 non-null  int64
 9   stadium_name              1492006 non-null  object
 10  stadium_seats             1492006 non-null  int64
 11  net_transfer_record       1492006 non-null  object
 12  last_season               1492006 non-null  int64
 13  game_id                   1492006 non-null  int64
 14  competition_id            1492006 non-null  object
 15  season                    1492006 non-null  int64
 16  round                     1492006 non-null  object
 17  date                      1492006 non-null  object
 18  home_club_id              1492006 non-null  int64
 19  away_club_id              1492006 non-null  int64
 20  home_club_goals           1492006 non-null  int64
 21  away_club_goals           1492006 non-null  int64
 22  home_club_position        1491910 non-null  float64
 23  away_club_position        1491910 non-null  float64
 24  home_club_manager_name    1487054 non-null  object
 25  away_club_manager_name    1487054 non-null  object
 26  stadium                   1490643 non-null  object
 27  attendance                1305701 non-null  float64
 28  referee                   1488323 non-null  object
 29  home_club_formation       1357210 non-null  object
 30  away_club_formation       1357075 non-null  object
 31  home_club_name            1492006 non-null  object
 32  away_club_name            1492006 non-null  object
 33  aggregate                 1492006 non-null  object
 34  competition_type          1492006 non-null  object
 35  competition_code          1492006 non-null  object
 36  name_y                    1492006 non-null  object
 37  sub_type                  1492006 non-null  object
 38  type                      1492006 non-null  object
 39  country_id                1492006 non-null  int64
 40  country_name              1492006 non-null  object
 41  domestic_league_code      1492006 non-null  object
 42  confederation             1492006 non-null  object
 43  is_major_national_league  1492006 non-null  bool
dtypes: bool(1), float64(5), int64(13), object(25)
memory usage: 490.9+ MB

In [18]:
df2['date'] = pd.to_datetime(df2['date'])

In [19]:
df2['date'].sort_values(ascending=True)

1292309   2012-07-13
795888    2012-07-13
761072    2012-07-13
789744    2012-07-13
1332950   2012-07-13
             ...
541271    2024-03-17
687847    2024-03-17
304316    2024-03-17
403652    2024-03-17
1035822   2024-03-17
Name: date, Length: 1492006, dtype: datetime64[ns]

In [20]:
start_date = '2018-08-01'
end_date = '2024-12-31'
mask = (df2['date'] >= start_date) & (df2['date'] <= end_date)
df3 = df2.loc[mask]

In [21]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 726179 entries, 123 to 1492005
Data columns (total 44 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   club_id                   726179 non-null  int64
 1   club_code                 726179 non-null  object
 2   name_x                    726179 non-null  object
 3   domestic_competition_id   726179 non-null  object
 4   squad_size                726179 non-null  int64
 5   average_age               675337 non-null  float64
 6   foreigners_number         726179 non-null  int64
 7   foreigners_percentage     660715 non-null  float64
 8   national_team_players     726179 non-null  int64
 9   stadium_name              726179 non-null  object
 10  stadium_seats             726179 non-null  int64
 11  net_transfer_record       726179 non-null  object
 12  last_season               726179 non-null  int64
 13  game_id                   726179 non-null  int64
 14  competition_id            726179 non-null  object
 15  season                    726179 non-null  int64
 16  round                     726179 non-null  object
 17  date                      726179 non-null  datetime64[ns]
 18  home_club_id              726179 non-null  int64
 19  away_club_id              726179 non-null  int64
 20  home_club_goals           726179 non-null  int64
 21  away_club_goals           726179 non-null  int64
 22  home_club_position        726083 non-null  float64
 23  away_club_position        726083 non-null  float64
 24  home_club_manager_name    724486 non-null  object
 25  away_club_manager_name    724486 non-null  object
 26  stadium                   726179 non-null  object
 27  attendance                560093 non-null  float64
 28  referee                   724430 non-null  object
 29  home_club_formation       719964 non-null  object
 30  away_club_formation       719829 non-null  object
 31  home_club_name            726179 non-null  object
 32  away_club_name            726179 non-null  object
 33  aggregate                 726179 non-null  object
 34  competition_type          726179 non-null  object
 35  competition_code          726179 non-null  object
 36  name_y                    726179 non-null  object
 37  sub_type                  726179 non-null  object
 38  type                      726179 non-null  object
 39  country_id                726179 non-null  int64
 40  country_name              726179 non-null  object
 41  domestic_league_code      726179 non-null  object
 42  confederation             726179 non-null  object
 43  is_major_national_league  726179 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(5), int64(13), object(24)
memory usage: 244.5+ MB

In [22]:
df3['date'].sort_values(ascending=True)

776557    2018-08-03
1331742   2018-08-03
150359    2018-08-03
689187    2018-08-03
786797    2018-08-03
             ...
1343928   2024-03-17
717359    2024-03-17
254237    2024-03-17
793096    2024-03-17
1238735   2024-03-17
Name: date, Length: 726179, dtype: datetime64[ns]

In [23]:
df3['country_name'].unique()

array(['Germany', 'Russia', 'Turkey', 'Italy', 'England', 'Belgium',
       'Denmark', 'Netherlands', 'Greece', 'Portugal', 'Scotland',
       'Spain', 'Ukraine', 'France'], dtype=object)

In [24]:
#국가 지정 
desired_countries = ['Germany', 'Italy', 'England', 'Spain', 'France']
df4 = df3[df3['country_name'].isin(desired_countries)]

In [25]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 351908 entries, 123 to 1492005
Data columns (total 44 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   club_id                   351908 non-null  int64
 1   club_code                 351908 non-null  object
 2   name_x                    351908 non-null  object
 3   domestic_competition_id   351908 non-null  object
 4   squad_size                351908 non-null  int64
 5   average_age               349719 non-null  float64
 6   foreigners_number         351908 non-null  int64
 7   foreigners_percentage     349719 non-null  float64
 8   national_team_players     351908 non-null  int64
 9   stadium_name              351908 non-null  object
 10  stadium_seats             351908 non-null  int64
 11  net_transfer_record       351908 non-null  object
 12  last_season               351908 non-null  int64
 13  game_id                   351908 non-null  int64
 14  competition_id            351908 non-null  object
 15  season                    351908 non-null  int64
 16  round                     351908 non-null  object
 17  date                      351908 non-null  datetime64[ns]
 18  home_club_id              351908 non-null  int64
 19  away_club_id              351908 non-null  int64
 20  home_club_goals           351908 non-null  int64
 21  away_club_goals           351908 non-null  int64
 22  home_club_position        351908 non-null  float64
 23  away_club_position        351908 non-null  float64
 24  home_club_manager_name    351844 non-null  object
 25  away_club_manager_name    351844 non-null  object
 26  stadium                   351908 non-null  object
 27  attendance                278940 non-null  float64
 28  referee                   351780 non-null  object
 29  home_club_formation       350169 non-null  object
 30  away_club_formation       350270 non-null  object
 31  home_club_name            351908 non-null  object
 32  away_club_name            351908 non-null  object
 33  aggregate                 351908 non-null  object
 34  competition_type          351908 non-null  object
 35  competition_code          351908 non-null  object
 36  name_y                    351908 non-null  object
 37  sub_type                  351908 non-null  object
 38  type                      351908 non-null  object
 39  country_id                351908 non-null  int64
 40  country_name              351908 non-null  object
 41  domestic_league_code      351908 non-null  object
 42  confederation             351908 non-null  object
 43  is_major_national_league  351908 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(5), int64(13), object(24)
memory usage: 118.5+ MB

In [26]:
df5 = df4[df4['competition_code'] == 'premier-league']
df5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 78588 entries, 515077 to 675618
Data columns (total 44 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   club_id                   78588 non-null  int64
 1   club_code                 78588 non-null  object
 2   name_x                    78588 non-null  object
 3   domestic_competition_id   78588 non-null  object
 4   squad_size                78588 non-null  int64
 5   average_age               78588 non-null  float64
 6   foreigners_number         78588 non-null  int64
 7   foreigners_percentage     78588 non-null  float64
 8   national_team_players     78588 non-null  int64
 9   stadium_name              78588 non-null  object
 10  stadium_seats             78588 non-null  int64
 11  net_transfer_record       78588 non-null  object
 12  last_season               78588 non-null  int64
 13  game_id                   78588 non-null  int64
 14  competition_id            78588 non-null  object
 15  season                    78588 non-null  int64
 16  round                     78588 non-null  object
 17  date                      78588 non-null  datetime64[ns]
 18  home_club_id              78588 non-null  int64
 19  away_club_id              78588 non-null  int64
 20  home_club_goals           78588 non-null  int64
 21  away_club_goals           78588 non-null  int64
 22  home_club_position        78588 non-null  float64
 23  away_club_position        78588 non-null  float64
 24  home_club_manager_name    78588 non-null  object
 25  away_club_manager_name    78588 non-null  object
 26  stadium                   78588 non-null  object
 27  attendance                62208 non-null  float64
 28  referee                   78588 non-null  object
 29  home_club_formation       78588 non-null  object
 30  away_club_formation       78588 non-null  object
 31  home_club_name            78588 non-null  object
 32  away_club_name            78588 non-null  object
 33  aggregate                 78588 non-null  object
 34  competition_type          78588 non-null  object
 35  competition_code          78588 non-null  object
 36  name_y                    78588 non-null  object
 37  sub_type                  78588 non-null  object
 38  type                      78588 non-null  object
 39  country_id                78588 non-null  int64
 40  country_name              78588 non-null  object
 41  domestic_league_code      78588 non-null  object
 42  confederation             78588 non-null  object
 43  is_major_national_league  78588 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(5), int64(13), object(24)
memory usage: 26.5+ MB

In [27]:
game_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 725287 entries, 0 to 725286
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   game_event_id     725287 non-null  object
 1   date              725287 non-null  object
 2   game_id           725287 non-null  int64
 3   minute            725287 non-null  int64
 4   type              725287 non-null  object
 5   club_id           725287 non-null  int64
 6   player_id         725287 non-null  int64
 7   description       405843 non-null  object
 8   player_in_id      439642 non-null  float64
 9   player_assist_id  47030 non-null   float64
dtypes: float64(2), int64(4), object(4)
memory usage: 55.3+ MB

In [28]:
df6 = pd.merge(df5, game_events, on = 'game_id')

In [29]:
players

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30494,1201580,Yusuf,Yılmaz,Yusuf Yılmaz,2023,6890,yusuf-yilmaz,Türkiye,Istanbul,Türkiye,...,right,193.0,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/yusuf-yilmaz/p...,TR1,İstanbul Başakşehir Futbol Kulübü,50000.0,50000.0
30495,1214946,Sid Ahmed,Aissaoui,Sid Ahmed Aissaoui,2023,2410,sid-ahmed-aissaoui,Algeria,Blida,Algeria,...,right,183.0,2026-06-30 00:00:00,Aniss Benchabane,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/sid-ahmed-aiss...,RU1,PFK CSKA Moskva,150000.0,150000.0
30496,1225269,Erdem,Çalık,Erdem Çalık,2023,3209,erdem-calik,Türkiye,Istanbul,Türkiye,...,right,NaN,2026-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/erdem-calik/pr...,TR1,Pendikspor,50000.0,50000.0
30497,1229924,Adama,Sidibeh,Adama Sidibeh,2023,2578,adama-sidibeh,NaN,NaN,The Gambia,...,NaN,NaN,2026-05-31 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/adama-sidibeh/...,SC1,Saint Johnstone Football Club,NaN,NaN
30498,1240762,Araphat,Mohammed,Araphat Mohammed,2023,2778,araphat-mohammed,NaN,NaN,Ghana,...,left,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/araphat-mohamm...,DK1,Fodbold Club Nordsjælland,NaN,NaN

In [30]:
df7 = pd.merge(df6, players, on='player_id', how='left')

In [31]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 811872 entries, 0 to 811871
Data columns (total 75 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   club_id_x                             811872 non-null  int64
 1   club_code                             811872 non-null  object
 2   name_x                                811872 non-null  object
 3   domestic_competition_id               811872 non-null  object
 4   squad_size                            811872 non-null  int64
 5   average_age                           811872 non-null  float64
 6   foreigners_number                     811872 non-null  int64
 7   foreigners_percentage                 811872 non-null  float64
 8   national_team_players                 811872 non-null  int64
 9   stadium_name                          811872 non-null  object
 10  stadium_seats                         811872 non-null  int64
 11  net_transfer_record                   811872 non-null  object
 12  last_season_x                         811872 non-null  int64
 13  game_id                               811872 non-null  int64
 14  competition_id                        811872 non-null  object
 15  season                                811872 non-null  int64
 16  round                                 811872 non-null  object
 17  date_x                                811872 non-null  datetime64[ns]
 18  home_club_id                          811872 non-null  int64
 19  away_club_id                          811872 non-null  int64
 20  home_club_goals                       811872 non-null  int64
 21  away_club_goals                       811872 non-null  int64
 22  home_club_position                    811872 non-null  float64
 23  away_club_position                    811872 non-null  float64
 24  home_club_manager_name                811872 non-null  object
 25  away_club_manager_name                811872 non-null  object
 26  stadium                               811872 non-null  object
 27  attendance                            672372 non-null  float64
 28  referee                               811872 non-null  object
 29  home_club_formation                   811872 non-null  object
 30  away_club_formation                   811872 non-null  object
 31  home_club_name                        811872 non-null  object
 32  away_club_name                        811872 non-null  object
 33  aggregate                             811872 non-null  object
 34  competition_type                      811872 non-null  object
 35  competition_code                      811872 non-null  object
 36  name_y                                811872 non-null  object
 37  sub_type                              811872 non-null  object
 38  type_x                                811872 non-null  object
 39  country_id                            811872 non-null  int64
 40  country_name                          811872 non-null  object
 41  domestic_league_code                  811872 non-null  object
 42  confederation                         811872 non-null  object
 43  is_major_national_league              811872 non-null  bool
 44  game_event_id                         811872 non-null  object
 45  date_y                                811872 non-null  object
 46  minute                                811872 non-null  int64
 47  type_y                                811872 non-null  object
 48  club_id_y                             811872 non-null  int64
 49  player_id                             811872 non-null  int64
 50  description                           421416 non-null  object
 51  player_in_id                          494820 non-null  float64
 52  player_assist_id                      55440 non-null   float64
 53  first_name                            739872 non-null  object
 54  last_name                             811728 non-null  object
 55  name                                  811728 non-null  object
 56  last_season_y                         811728 non-null  float64
 57  current_club_id                       811728 non-null  float64
 58  player_code                           811728 non-null  object
 59  country_of_birth                      795060 non-null  object
 60  city_of_birth                         811656 non-null  object
 61  country_of_citizenship                795132 non-null  object
 62  date_of_birth                         811728 non-null  object
 63  sub_position                          811728 non-null  object
 64  position                              811728 non-null  object
 65  foot                                  810756 non-null  object
 66  height_in_cm                          811620 non-null  float64
 67  contract_expiration_date              754452 non-null  object
 68  agent_name                            584208 non-null  object
 69  image_url                             811728 non-null  object
 70  url                                   811728 non-null  object
 71  current_club_domestic_competition_id  811728 non-null  object
 72  current_club_name                     811728 non-null  object
 73  market_value_in_eur                   811692 non-null  float64
 74  highest_market_value_in_eur           811692 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(12), int64(16), object(45)
memory usage: 459.1+ MB

In [32]:
df7 = df7.drop(['url', 'image_url', 'first_name', 'last_name'], axis=1)

In [33]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 811872 entries, 0 to 811871
Data columns (total 71 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   club_id_x                             811872 non-null  int64
 1   club_code                             811872 non-null  object
 2   name_x                                811872 non-null  object
 3   domestic_competition_id               811872 non-null  object
 4   squad_size                            811872 non-null  int64
 5   average_age                           811872 non-null  float64
 6   foreigners_number                     811872 non-null  int64
 7   foreigners_percentage                 811872 non-null  float64
 8   national_team_players                 811872 non-null  int64
 9   stadium_name                          811872 non-null  object
 10  stadium_seats                         811872 non-null  int64
 11  net_transfer_record                   811872 non-null  object
 12  last_season_x                         811872 non-null  int64
 13  game_id                               811872 non-null  int64
 14  competition_id                        811872 non-null  object
 15  season                                811872 non-null  int64
 16  round                                 811872 non-null  object
 17  date_x                                811872 non-null  datetime64[ns]
 18  home_club_id                          811872 non-null  int64
 19  away_club_id                          811872 non-null  int64
 20  home_club_goals                       811872 non-null  int64
 21  away_club_goals                       811872 non-null  int64
 22  home_club_position                    811872 non-null  float64
 23  away_club_position                    811872 non-null  float64
 24  home_club_manager_name                811872 non-null  object
 25  away_club_manager_name                811872 non-null  object
 26  stadium                               811872 non-null  object
 27  attendance                            672372 non-null  float64
 28  referee                               811872 non-null  object
 29  home_club_formation                   811872 non-null  object
 30  away_club_formation                   811872 non-null  object
 31  home_club_name                        811872 non-null  object
 32  away_club_name                        811872 non-null  object
 33  aggregate                             811872 non-null  object
 34  competition_type                      811872 non-null  object
 35  competition_code                      811872 non-null  object
 36  name_y                                811872 non-null  object
 37  sub_type                              811872 non-null  object
 38  type_x                                811872 non-null  object
 39  country_id                            811872 non-null  int64
 40  country_name                          811872 non-null  object
 41  domestic_league_code                  811872 non-null  object
 42  confederation                         811872 non-null  object
 43  is_major_national_league              811872 non-null  bool
 44  game_event_id                         811872 non-null  object
 45  date_y                                811872 non-null  object
 46  minute                                811872 non-null  int64
 47  type_y                                811872 non-null  object
 48  club_id_y                             811872 non-null  int64
 49  player_id                             811872 non-null  int64
 50  description                           421416 non-null  object
 51  player_in_id                          494820 non-null  float64
 52  player_assist_id                      55440 non-null   float64
 53  name                                  811728 non-null  object
 54  last_season_y                         811728 non-null  float64
 55  current_club_id                       811728 non-null  float64
 56  player_code                           811728 non-null  object
 57  country_of_birth                      795060 non-null  object
 58  city_of_birth                         811656 non-null  object
 59  country_of_citizenship                795132 non-null  object
 60  date_of_birth                         811728 non-null  object
 61  sub_position                          811728 non-null  object
 62  position                              811728 non-null  object
 63  foot                                  810756 non-null  object
 64  height_in_cm                          811620 non-null  float64
 65  contract_expiration_date              754452 non-null  object
 66  agent_name                            584208 non-null  object
 67  current_club_domestic_competition_id  811728 non-null  object
 68  current_club_name                     811728 non-null  object
 69  market_value_in_eur                   811692 non-null  float64
 70  highest_market_value_in_eur           811692 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(12), int64(16), object(41)
memory usage: 434.4+ MB

In [34]:
df7

,club_id_x,club_code,name_x,domestic_competition_id,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,...,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,26,25.4,20,76.9,21,Tottenham Hotspur Stadium,...,Centre-Back,Defender,right,189.0,2023-12-31 00:00:00,Bertolucci Sports,GB1,Arsenal Football Club,500000.0,30000000.0
1,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,26,25.4,20,76.9,21,Tottenham Hotspur Stadium,...,Left Winger,Attack,right,175.0,2024-06-30 00:00:00,Sports Invest UK ltd,GB1,Fulham Football Club,3000000.0,50000000.0
2,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,26,25.4,20,76.9,21,Tottenham Hotspur Stadium,...,Left-Back,Defender,left,173.0,2024-06-30 00:00:00,Unique Sports Group,GB1,Huddersfield Town,150000.0,2000000.0
3,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,26,25.4,20,76.9,21,Tottenham Hotspur Stadium,...,Centre-Back,Defender,right,188.0,2024-06-30 00:00:00,PRO Profil GmbH,GB1,Huddersfield Town,500000.0,7000000.0
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,26,25.4,20,76.9,21,Tottenham Hotspur Stadium,...,Right Winger,Attack,both,167.0,2024-06-30 00:00:00,Bahía Internacional,IT1,Società Sportiva Lazio S.p.A.,1500000.0,30000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811867,984,west-bromwich-albion,West Bromwich Albion,GB1,25,27.8,8,32.0,4,The Hawthorns,...,Centre-Forward,Attack,right,185.0,2023-06-30 00:00:00,CAA Base Ltd,GB1,Burnley Football Club,1000000.0,10000000.0
811868,984,west-bromwich-albion,West Bromwich Albion,GB1,25,27.8,8,32.0,4,The Hawthorns,...,Right Winger,Attack,right,172.0,NaN,4ComM,GB1,Tottenham Hotspur Football Club,6000000.0,40000000.0
811869,984,west-bromwich-albion,West Bromwich Albion,GB1,25,27.8,8,32.0,4,The Hawthorns,...,Right-Back,Defender,right,180.0,2023-05-31 00:00:00,NaN,GB1,Burnley Football Club,250000.0,5000000.0
811870,984,west-bromwich-albion,West Bromwich Albion,GB1,25,27.8,8,32.0,4,The Hawthorns,...,Centre-Forward,Attack,right,188.0,2027-06-30 00:00:00,CK66,L1,FC Bayern München,110000000.0,150000000.0
811871,984,west-bromwich-albion,West Bromwich Albion,GB1,25,27.8,8,32.0,4,The Hawthorns,...,Right-Back,Defender,right,183.0,2026-06-30 00:00:00,AIS Football,GB1,Tottenham Hotspur Football Club,18000000.0,30000000.0